services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresPayment
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgresPayment"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-server:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "postgresPayment"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: